name: Node CI
# on – определяет события, которые запускают воркфлоу
on: 
  - push
  - pull_request

env:
  CI: true

jobs:
  # build – произвольно выбранное имя задания
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [ 14, 16, 18 ]
  
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v2
      # Step's name
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v2
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: make install
      - run: make lint